# Documentation for Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# Additional GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - moncatii

on:
  push:
    branches:
      - devbee
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build ./Moncati-Car-API/Moncati-Car-API.csproj --configuration Release

      - name: Publish with dotnet
        run: dotnet publish ./Moncati-Car-API/Moncati-Car-API.csproj -c Release -o D:/moncati/moncati/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: D:/moncati/moncati/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for JWT requests

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_050C7B08BF944C1D869D98C5FDF993D7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2D4676692EA74CE9802C46772E000811 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CCAA28FB2B4A415EB438B6A6BF3D3B24 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'moncatii'
          slot-name: 'Production'
          package: .
